[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install uv", "uv pip install --system -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
